### ISSUE TITLE
Adakah video penjelasan atau demo nya bang ?

### ISSUE THREAD

**Issue by ackaminang** [kevinopee/Autobuy-Shopee-ID#2]

**Comment by kevinopee** [comment]
> _No description provided._

Kalo situ udah familiar sama python, pasti paham sih dari alur. Dan saya juga sudah sertain kok langkah2 di README. Thanks sblmnya

**Comment by ackaminang** [comment]
Yahh bang udah running code nya, tapi kok file .pkl nya nda otomatis di generate pdhl sudah sesuai step

**Comment by kevinopee** [comment]
> Yahh bang udah running code nya, tapi kok file .pkl nya nda otomatis di generate pdhl sudah sesuai step

Saya abis coba, berhasil kok. Kalo emg fail, apus lg dulu .pkl nya, login lg dr awal.

**Comment by ackaminang** [comment]
Traceback (most recent call last):
  File "C:\Users\Aldio Kaminang\PycharmProjects\pythonProject\venv\Autobuy-Shopee-ID\Shopee Autobuy\save_cookies.py", line 75, in <module>
    main()
  File "C:\Users\Aldio Kaminang\PycharmProjects\pythonProject\venv\Autobuy-Shopee-ID\Shopee Autobuy\save_cookies.py", line 71, in main
    login(ac.email_phone_number, ac.passwd)
  File "C:\Users\Aldio Kaminang\PycharmProjects\pythonProject\venv\Autobuy-Shopee-ID\Shopee Autobuy\save_cookies.py", line 38, in login
    click_login = WD(browser, 60).until(EC.element_to_be_clickable((
  File "C:\Users\Aldio Kaminang\PycharmProjects\pythonProject\venv\lib\site-packages\selenium\webdriver\support\wait.py", line 80, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message:  

Error kek gitu bang

**Comment by kevinopee** [comment]
> Traceback (most recent call last):
> File "C:\Users\Aldio Kaminang\PycharmProjects\pythonProject\venv\Autobuy-Shopee-ID\Shopee Autobuy\save_cookies.py", line 75, in
> main()
> File "C:\Users\Aldio Kaminang\PycharmProjects\pythonProject\venv\Autobuy-Shopee-ID\Shopee Autobuy\save_cookies.py", line 71, in main
> login(ac.email_phone_number, ac.passwd)
> File "C:\Users\Aldio Kaminang\PycharmProjects\pythonProject\venv\Autobuy-Shopee-ID\Shopee Autobuy\save_cookies.py", line 38, in login
> click_login = WD(browser, 60).until(EC.element_to_be_clickable((
> File "C:\Users\Aldio Kaminang\PycharmProjects\pythonProject\venv\lib\site-packages\selenium\webdriver\support\wait.py", line 80, in until
> raise TimeoutException(message, screen, stacktrace)
> selenium.common.exceptions.TimeoutException: Message:
> 
> Error kek gitu bang

Situ udah isi data akun di account.py blm? Kalo udah, itu kira kira pas bagian verif kode nya itu diisi manual. Saya udh debug dan bisa-bisa aja, itu timeout mungkin karna situ isi verif kode nya salah. Mohon di cek lagi ya, di readme

**Comment by ackaminang** [comment]
Udah di isi kok bang yg di account.py, verif codenya sudah sesuai sih.

**Comment by kevinopee** [comment]
> Udah di isi kok bang yg di account.py, verif codenya sudah sesuai sih.

Wait saya kirim video berhasilnya aja ya, biar make sure kalo code ini running. Sisanya nanti troubleshoot sendiri codingan saya ya, pull request aja.

**Comment by ackaminang** [comment]
https://drive.google.com/file/d/1yZDG5Ks4DW151sBkz-wRLIjL12aRymOE/view?usp=sharing ini klo dari saya bang, mungkin ada step yang salah hehehe, maaf merepotkan bang. Okeydeh ditunggu videonya

**Comment by kevinopee** [comment]
> https://drive.google.com/file/d/1yZDG5Ks4DW151sBkz-wRLIjL12aRymOE/view?usp=sharing ini klo dari saya bang, mungkin ada step yang salah hehehe, maaf merepotkan bang. Okeydeh ditunggu videonya

Cookie :
https://drive.google.com/file/d/1zBPi98QdxQXnckC9YAvbbUqZb1pgfN2k/view?usp=sharing

Usage:
https://drive.google.com/file/d/1hSO3N-60qha1riS-1YY1f4kSPo_FiavN/view?usp=sharing

**Comment by ackaminang** [comment]
[1656:10328:1229/170621.855:ERROR:device_event_log_impl.cc(211)] [17:06:21.854] USB: usb_device_handle_win.cc:1020 Failed to read descriptor from node connection: A device attached to the system is not functioning. (0x1F)  
Bang itu error knpa ya ? Padahal sudah sesuai step, file untuk akunnya tidak di generate otomatis, apakah ada yang salah ?

**Comment by ackaminang** [comment]
Bang saya sudah sampai di step barang tercheckout, nah setelah itu script nya gak otomatis lagi :v pdhl udh save akun plus pin shopee pay nya hehehe. Apa mungkin ada kesalahan dari saya ?

**Comment by kevinopee** [comment]
> Bang saya sudah sampai di step barang tercheckout, nah setelah itu script nya gak otomatis lagi :v pdhl udh save akun plus pin shopee pay nya hehehe. Apa mungkin ada kesalahan dari saya ?

Itu di troubleshoot sendiri, nanti ane keluarin versi baru yg ane pake setelah flash sale 1.1 yaa 😂😉

**Comment by ackaminang** [comment]
Ohh okeydeh bang, thank you doakan menang juga hahahaha

**Comment by ackaminang** [comment]
Bang kayaknya dari pihak shopee, sengaja meurbah xpath dari tombol buat pesanan itu berbeda tiap harinya, itu dari pengamatan saya sih hehehe

**Comment by kevinopee** [comment]
> Bang kayaknya dari pihak shopee, sengaja meurbah xpath dari tombol buat pesanan itu berbeda tiap harinya, itu dari pengamatan saya sih hehehe

Perhaps it wasn't bro hehehe, clue : input pada div element, mangats

**Comment by ackaminang** [comment]
Lahh trus gmna dong bang bahahaha, ksih spoiler dong
